version: "3.7"
services:
  python:
    build:
      context: .
      dockerfile: Docker/pi/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
    volumes:
      - ./App:/app:cached
