version: "3.7"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
    volumes:
      - ./MainApplication:/app:cached
