version: "2"
services:
  nginx:
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:1.13.7
    depends_on:
      - python
    container_name: nginx
    networks:
      - cam-network
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']

  python:
    privileged: true
    networks:
      cam-network:
        aliases:
          - flask-app
    build:
      context: .
      dockerfile: Docker/server/Dockerfile
    command:  gunicorn --bind=0.0.0.0:5000 --threads 5 wsgi:app
    volumes:
      - ./App:/app:cached

networks:
    cam-network: